import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Template({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
} 